version: "3"
services:
  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/src/elciess-ms-auth-controll
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    volumes: 
      - ./dist/:/usr/src/elciess-ms-auth-controll/dist/
      - ./package.json:/usr/src/elciess-ms-auth-controll/package.json
    ports: 
      - "5050:5050"
      - "9222:9222"