version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports: 
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    image: elciess-ms-auth-controll
    restart: always
    command: npm run debug
    volumes: 
      - ./dist:/usr/src/elciess-ms-auth-controll/dist
      - ./package.json:/usr/src/elciess-ms-auth-controll/package.json
    ports: 
      - "5050:5050"
      - "9222:9222"
    links: 
      - mongo